# Generated by Django 4.2.13 on 2026-05-15 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('freelancer', 'Freelancer'), ('admin', 'Admin')], max_length=16)),
                ('entity', models.CharField(help_text="Table name, e.g. 'tickets'", max_length=64)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='free', max_length=32)),
                ('gstin', models.CharField(blank=True, help_text='GST registration number (B2B customers)', max_length=15)),
                ('oauth_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('oauth_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skill tags, e.g. linux,sap,vmware')),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('ad_hoc', 'Ad Hoc'), ('unavailable', 'Unavailable')], default='ad_hoc', max_length=32)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('active', models.BooleanField(default=True)),
                ('payout_mode', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI')], max_length=32)),
                ('payout_details', models.JSONField(default=dict, help_text='Encrypted bank/UPI details')),
                ('contract_signed', models.BooleanField(default=False)),
                ('onboarding_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=16, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('desktop', 'Desktop / Laptop Support'), ('linux', 'Linux Provisioning'), ('windows', 'Windows Provisioning'), ('patching', 'OS Patching'), ('security', 'Security Hardening'), ('vmware', 'VMware / Hypervisor'), ('sap', 'SAP Basis Lite')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending_payment', max_length=32)),
                ('remote_session_url', models.URLField(blank=True, max_length=512)),
                ('external_ticket_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='support_app.freelancer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='support_app.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('author_type', models.CharField(choices=[('customer', 'Customer'), ('freelancer', 'Freelancer'), ('admin', 'Admin')], max_length=16)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support_app.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_url', models.URLField(max_length=1024)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('uploaded_by', models.UUIDField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support_app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('silver', 'Silver — ₹1,499/mo'), ('gold', 'Gold — ₹3,499/mo'), ('platinum', 'Platinum — ₹7,999/mo')], max_length=32)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=16)),
                ('tickets_used', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='support_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=16)),
                ('plan', models.CharField(default='default', max_length=32)),
                ('first_response_seconds', models.IntegerField()),
                ('resolution_seconds', models.IntegerField()),
            ],
            options={
                'verbose_name': 'SLA Policy',
                'verbose_name_plural': 'SLA Policies',
                'unique_together': {('service_type', 'severity', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='SLALog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('first_response', 'First Response'), ('resolved', 'Resolved'), ('breach', 'SLA Breach')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_seconds', models.IntegerField(blank=True, null=True)),
                ('actual_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('met', 'Met'), ('missed', 'Missed'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_logs', to='support_app.ticket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('invoice_number', models.CharField(blank=True, max_length=64, unique=True)),
                ('payment_type', models.CharField(choices=[('consulting_fee', 'Consulting Fee'), ('resolution_fee', 'Resolution Fee'), ('subscription', 'Subscription'), ('refund', 'Refund')], max_length=32)),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('payu', 'PayU')], default='razorpay', max_length=32)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='support_app.customer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_app.subscription')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='support_app.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CSATSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(help_text='Rating from 1 (very unhappy) to 5 (very happy)')),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_app.customer')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csat_survey', to='support_app.ticket')),
            ],
            options={
                'verbose_name': 'CSAT Survey',
                'verbose_name_plural': 'CSAT Surveys',
            },
        ),
    ]
