# Generated by Django 4.2.13 on 2026-05-19 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Ticket Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('severity_changed', 'Severity Changed'), ('assigned', 'Assigned to Freelancer'), ('unassigned', 'Unassigned'), ('reassigned', 'Reassigned'), ('comment_added', 'Comment Added'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('sla_breached', 'SLA Breached')], max_length=32)),
                ('from_value', models.CharField(blank=True, max_length=255)),
                ('to_value', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('initial', 'Initial Assignment'), ('reassigned', 'Reassigned'), ('freelancer_unavailable', 'Freelancer Unavailable'), ('customer_request', 'Customer Request'), ('admin_action', 'Admin Action'), ('auto_assigned', 'Auto-Assigned')], default='initial', max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ticket Assignment',
                'verbose_name_plural': 'Ticket Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='author_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_breach_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('low', 'Low — Minor inconvenience'), ('medium', 'Medium — Partial degradation'), ('high', 'High — Major function blocked'), ('critical', 'Critical — Complete outage')], default='medium', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting for Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending_payment', max_length=32),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file_size',
            field=models.PositiveIntegerField(help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'customer'], name='idx_ticket_status_customer'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_ticket_assigned_status'),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='support_app.freelancer'),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='support_app.ticket'),
        ),
        migrations.AddField(
            model_name='ticketactivitylog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketactivitylog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='support_app.ticket'),
        ),
    ]
