# Generated by Django 4.2.13 on 2026-05-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0003_phase4_notification_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read'),
        ),
        migrations.AddIndex(
            model_name='ticketactivitylog',
            index=models.Index(fields=['ticket', 'action'], name='idx_activity_log_ticket_action'),
        ),
    ]
