# Generated by Django 4.2.13 on 2026-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0006_approve_pending_freelancers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
