# Generated by Django 4.2.13 on 2026-06-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0007_add_is_verified_to_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='payout_details',
            field=models.JSONField(default=dict, help_text='Bank/UPI payout details — exclude from all serializers until encrypted at rest'),
        ),
    ]
