# Generated by Django 4.2.13 on 2026-06-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0008_alter_freelancer_payout_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("freelancer", "Freelancer"),
                    ("admin", "Admin"),
                    ("operations_manager", "Operations Manager"),
                ],
                default="customer",
                max_length=32,
            ),
        ),
    ]
