# Generated by Django 4.2.13 on 2026-06-22 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0009_add_operations_manager_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "required_skills",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated skill tags, e.g. linux,sap,vmware",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoleChangeAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_email", models.EmailField(blank=True, max_length=254)),
                (
                    "old_role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("freelancer", "Engineer"),
                            ("admin", "Super Admin"),
                            ("operations_manager", "Operations Manager"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "new_role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("freelancer", "Engineer"),
                            ("admin", "Super Admin"),
                            ("operations_manager", "Operations Manager"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_change_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Change Audit",
                "verbose_name_plural": "Role Change Audits",
                "ordering": ["-timestamp"],
            },
        ),
    ]
