# Generated by Django 4.2.13 on 2026-06-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0010_role_management"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("freelancer", "Freelancer"),
                    ("admin", "Admin"),
                    ("operations_manager", "Operations Manager"),
                    ("finance_manager", "Finance Manager"),
                    ("support_agent", "Support Agent"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("freelancer", "Freelancer"),
                    ("admin", "Admin"),
                    ("operations_manager", "Operations Manager"),
                    ("finance_manager", "Finance Manager"),
                    ("support_agent", "Support Agent"),
                ],
                default="customer",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rolechangeaudit",
            name="new_role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("freelancer", "Engineer"),
                    ("admin", "Super Admin"),
                    ("operations_manager", "Operations Manager"),
                    ("finance_manager", "Finance Manager"),
                    ("support_agent", "Support Agent"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rolechangeaudit",
            name="old_role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("freelancer", "Engineer"),
                    ("admin", "Super Admin"),
                    ("operations_manager", "Operations Manager"),
                    ("finance_manager", "Finance Manager"),
                    ("support_agent", "Support Agent"),
                ],
                max_length=32,
            ),
        ),
    ]
