# Generated by Django 4.2.13 on 2026-06-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0011_add_new_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketactivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Ticket Created"),
                    ("status_changed", "Status Changed"),
                    ("priority_changed", "Priority Changed"),
                    ("severity_changed", "Severity Changed"),
                    ("assigned", "Assigned to Freelancer"),
                    ("unassigned", "Unassigned"),
                    ("reassigned", "Reassigned"),
                    ("comment_added", "Comment Added"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("reopened", "Reopened"),
                    ("sla_breached", "SLA Breached"),
                    ("escalated", "Escalated"),
                ],
                max_length=32,
            ),
        ),
    ]
