# Generated by Django 4.2.13 on 2026-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0012_add_escalated_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("desktop", "Desktop / Laptop Support"),
                    ("linux", "Linux Provisioning"),
                    ("windows", "Windows Provisioning"),
                    ("patching", "OS Patching"),
                    ("security", "Security Hardening"),
                    ("vmware", "VMware / Hypervisor"),
                    ("sap", "SAP Basis Lite"),
                    ("microsoft365", "Microsoft 365 / Exchange"),
                ],
                max_length=32,
            ),
        ),
    ]
