# Generated by Django 4.2.13 on 2026-07-13 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0024_remove_waiting_customer_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="KBArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Article content, written in Markdown."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop / Laptop Support"),
                            ("linux", "Linux Provisioning"),
                            ("windows", "Windows Provisioning"),
                            ("patching", "OS Patching"),
                            ("security", "Security Hardening"),
                            ("vmware", "VMware / Hypervisor"),
                            ("sap", "SAP Basis Lite"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=32,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterField(
            model_name="ticketactivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Ticket Created"),
                    ("status_changed", "Status Changed"),
                    ("severity_changed", "Severity Changed"),
                    ("assigned", "Assigned to Freelancer"),
                    ("unassigned", "Unassigned"),
                    ("reassigned", "Reassigned"),
                    ("comment_added", "Comment Added"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("reopened", "Reopened"),
                    ("sla_breached", "SLA Breached"),
                    ("escalated", "Escalated"),
                    ("kb_article_linked", "Knowledge Base Article Linked"),
                    ("ai_suggestion_used", "AI Suggestion Used"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="KBArticleTicketLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_links",
                        to="support_app.kbarticle",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_links_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_links",
                        to="support_app.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-linked_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="kbarticleticketlink",
            constraint=models.UniqueConstraint(
                fields=("article", "ticket"), name="uniq_kb_article_ticket_link"
            ),
        ),
        migrations.AddIndex(
            model_name="kbarticle",
            index=models.Index(
                fields=["status", "category"], name="idx_kb_status_category"
            ),
        ),
    ]
