# Generated by Django 4.2.13 on 2026-07-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0026_replace_service_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancer",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated skill tags, e.g. aws,kubernetes,server_admin",
            ),
        ),
        migrations.AlterField(
            model_name="kbarticle",
            name="category",
            field=models.CharField(
                choices=[
                    ("laptop_desktop", "Laptop / Desktop Support"),
                    ("server_admin", "Server Administration Support"),
                    ("aws", "AWS Support"),
                    ("azure", "Azure Support"),
                    ("kubernetes", "Kubernetes Support"),
                    ("database", "Database Support"),
                    ("devops_cicd", "DevOps CI/CD Support"),
                    ("infra_automation", "Infrastructure Platform Automation Support"),
                    ("general", "General"),
                ],
                default="general",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="required_skills",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated skill tags, e.g. aws,kubernetes,server_admin",
                max_length=500,
            ),
        ),
    ]
