# Generated by Django 4.2.13 on 2026-07-19 07:05
"""
Phase 3 of the Admin Portal audit: makes the `Service` model the single
source of truth for the customer-facing catalog (previously a hardcoded
Python list, service_catalog.SERVICE_CATALOG — see that module's updated
docstring). This data migration seeds the 8 services that list already
defined, with the exact same key/name/resolution_fee/scope values, so
every existing Ticket.service_type value continues to resolve correctly
and pricing doesn't change for any existing or in-flight ticket.

category/icon/display_order/estimated_*_minutes are new, admin-editable
metadata with sensible defaults — not present in the old hardcoded list.
"""

from django.db import migrations, models

# Mirrors service_catalog.SERVICE_CATALOG at the time of this migration —
# intentionally a static snapshot, not an import, so this migration's
# behavior never changes even if that module is edited or removed later.
_SEED_SERVICES = [
    {
        "key": "laptop_desktop", "name": "Laptop / Desktop Support",
        "resolution_fee": 499, "category": "Endpoint Support", "icon": "💻",
        "description": "Business endpoint support including Windows, macOS, Linux desktops, laptops, software installation, troubleshooting, hardware diagnostics and end-user support",
        "estimated_response_minutes": 60, "estimated_resolution_minutes": 480,
    },
    {
        "key": "server_admin", "name": "Server Administration Support",
        "resolution_fee": 999, "category": "Infrastructure", "icon": "🖥️",
        "description": "Windows Server and Linux Server administration including Active Directory, patching, monitoring, storage, virtualization and server maintenance",
        "estimated_response_minutes": 90, "estimated_resolution_minutes": 720,
    },
    {
        "key": "aws", "name": "AWS Support",
        "resolution_fee": 1499, "category": "Cloud", "icon": "☁️",
        "description": "Amazon Web Services administration including EC2, VPC, IAM, S3, RDS, CloudWatch, Load Balancers and related cloud services",
        "estimated_response_minutes": 120, "estimated_resolution_minutes": 1440,
    },
    {
        "key": "azure", "name": "Azure Support",
        "resolution_fee": 1499, "category": "Cloud", "icon": "☁️",
        "description": "Microsoft Azure administration including Virtual Machines, Azure AD, Networking, Storage, Resource Groups, Monitoring and Identity",
        "estimated_response_minutes": 120, "estimated_resolution_minutes": 1440,
    },
    {
        "key": "kubernetes", "name": "Kubernetes Support",
        "resolution_fee": 1799, "category": "Platform Engineering", "icon": "☸️",
        "description": "Container orchestration, cluster management, deployments, scaling, ingress, troubleshooting and Kubernetes platform operations",
        "estimated_response_minutes": 120, "estimated_resolution_minutes": 1440,
    },
    {
        "key": "database", "name": "Database Support",
        "resolution_fee": 1299, "category": "Data", "icon": "🗄️",
        "description": "Administration, monitoring, backup, tuning and troubleshooting for PostgreSQL, MySQL, SQL Server, MongoDB and similar databases",
        "estimated_response_minutes": 90, "estimated_resolution_minutes": 1080,
    },
    {
        "key": "devops_cicd", "name": "DevOps CI/CD Support",
        "resolution_fee": 1499, "category": "Platform Engineering", "icon": "🔁",
        "description": "GitHub Actions, GitLab CI, Jenkins, Docker pipelines, deployments, release automation, infrastructure delivery and CI/CD troubleshooting",
        "estimated_response_minutes": 120, "estimated_resolution_minutes": 1440,
    },
    {
        "key": "infra_automation", "name": "Infrastructure Platform Automation Support",
        "resolution_fee": 1799, "category": "Platform Engineering", "icon": "⚙️",
        "description": "Infrastructure as Code, automation and configuration management including Terraform, Ansible, scripting, provisioning and platform automation",
        "estimated_response_minutes": 120, "estimated_resolution_minutes": 1440,
    },
]


def seed_canonical_services(apps, schema_editor):
    Service = apps.get_model("support_app", "Service")
    for order, entry in enumerate(_SEED_SERVICES):
        Service.objects.get_or_create(
            key=entry["key"],
            defaults={
                "name": entry["name"],
                "category": entry["category"],
                "icon": entry["icon"],
                "description": entry["description"],
                "resolution_fee": entry["resolution_fee"],
                "estimated_response_minutes": entry["estimated_response_minutes"],
                "estimated_resolution_minutes": entry["estimated_resolution_minutes"],
                "display_order": order,
                "is_active": True,
                "is_available": True,
            },
        )


def noop_reverse(apps, schema_editor):
    # Intentionally a no-op: reversing would delete rows that may since have
    # been edited by an admin or referenced by real tickets — not safe to
    # auto-reverse. Matches 0026_replace_service_catalog's precedent.
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "support_app",
            "0027_alter_freelancer_skills_alter_kbarticle_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.RemoveField(
            model_name="service",
            name="status",
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="service",
            name="display_order",
            field=models.IntegerField(
                default=0, help_text="Lower numbers appear first in the catalog."
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="estimated_resolution_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Typical resolution time shown to customers, in minutes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="estimated_response_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Typical first-response time shown to customers, in minutes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Highlight this service in the customer catalog.",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.CharField(
                blank=True,
                default="🛠️",
                help_text="A single emoji shown next to the service name — no code change needed to add new icons.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="False = archived, hidden from the customer catalog.",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="False = temporarily unavailable — still listed but greyed out; blocks new tickets.",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="key",
            field=models.SlugField(default="", max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="resolution_fee",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Base resolution fee in ₹ (pre-GST, before severity surcharge).",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Customer-facing description of what this service covers.",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="service_type",
            field=models.CharField(max_length=32),
        ),
        migrations.RunPython(seed_canonical_services, noop_reverse),
    ]
