# Generated by Django 4.2.13 on 2026-07-20 13:05

from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify
import django.db.models.deletion
import uuid


def backfill_organizations(apps, schema_editor):
    """
    Every Customer that existed before this migration gets an
    auto-created Organization (named after their company, or a fallback
    derived from their email if company is blank) and becomes its
    org_admin — preserving "one customer belongs to one organization"
    for pre-existing accounts without requiring any user action.
    Freelancers/staff are untouched — Organization only attaches to
    Customer, per this migration's own AddField.
    """
    Customer = apps.get_model("support_app", "Customer")
    Organization = apps.get_model("support_app", "Organization")
    OrganizationMembership = apps.get_model("support_app", "OrganizationMembership")

    existing_slugs = set(Organization.objects.values_list("slug", flat=True))

    for customer in Customer.objects.filter(organization__isnull=True).select_related("user"):
        base_name = customer.company.strip() or f"{customer.user.email.split('@')[0]}'s Organization"
        base_slug = slugify(base_name) or "organization"
        slug = base_slug
        suffix = 1
        while slug in existing_slugs:
            suffix += 1
            slug = f"{base_slug}-{suffix}"
        existing_slugs.add(slug)

        org = Organization.objects.create(id=uuid.uuid4(), name=base_name, slug=slug)
        OrganizationMembership.objects.create(
            id=uuid.uuid4(), organization=org, user=customer.user, role="org_admin",
        )
        customer.organization = org
        customer.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0028_service_catalog_management"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("org_admin", "Organization Admin"),
                            ("org_member", "Member"),
                        ],
                        default="org_member",
                        max_length=32,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="support_app.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("org_admin", "Organization Admin"),
                            ("org_member", "Member"),
                        ],
                        default="org_member",
                        max_length=32,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="support_app.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="support_app.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"), name="unique_org_membership"
            ),
        ),
        migrations.RunPython(backfill_organizations, migrations.RunPython.noop),
    ]
