# Generated by Django 4.2.13 on 2026-07-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0029_organizations_multi_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("freelancer", "Freelancer"),
                    ("admin", "Admin"),
                    ("operations_manager", "Operations Manager"),
                    ("finance_manager", "Finance Manager"),
                    ("support_agent", "Support Agent"),
                    ("system", "System"),
                ],
                max_length=32,
            ),
        ),
    ]
