# Generated by Django 4.2.13 on 2026-07-31 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0031_staff_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            (
                                "registration_privacy_policy",
                                "Registration — Privacy Policy & Terms",
                            )
                        ],
                        max_length=64,
                    ),
                ),
                ("policy_version", models.CharField(max_length=32)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="anonymized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["deletion_requested_at"], name="idx_user_deletion_requested"
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
